spring:
  application:
    name: springcloud-hello-zipkin
  main:
    allow-bean-definition-overriding: true # 解决The bean 'characterEncodingFilter'

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false