spring:
  application:
    name: springcloud-hello-service-order1
  zipkin:
    base-url: http://192.168.25.133:9411
  cloud:
    loadbalancer:
      retry:
        enabled: true  # \u914D\u7F6Eribbon \u91CD\u8BD5 \u9ED8\u8BA4\u4E0D\u91CD\u8BD5

server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.25.133:8761/eureka/

springcloud-hello-service-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 2000 # Ribbon\u7684\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
    ReadTimeout: 6000 # Ribbon\u7684\u6570\u636E\u8BFB\u53D6\u8D85\u65F6\u65F6\u95F4
    OkToRetryOnAllOperations: true # \u662F\u5426\u5BF9\u6240\u6709\u64CD\u4F5C\u90FD\u8FDB\u884C\u91CD\u8BD5
    MaxAutoRetriesNextServer: 3 # \u5207\u6362\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570
    MaxAutoRetries: 1 # \u5BF9\u5F53\u524D\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570

feign:
  hystrix:
    enabled: true # \u5F00\u542FFeign\u7684\u7194\u65AD\u529F\u80FD
